try{
function f(a){throw a;}var h=void 0,k=!0,m=null,p=!1,s,aa=[];function ba(a){return function(){return aa[a].apply(this,arguments)}}function ca(a,b){return aa[a]=b}var da=da||{},t=this;function ea(a){a.Xb=function(){return a.$J?a.$J:a.$J=new a}}
function fa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return a!==h}function ga(a){return"array"==fa(a)}function ha(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ia(a){return"function"==fa(a)}function ja(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}function ka(a){return a[la]||(a[la]=++ma)}var la="closure_uid_"+(1E9*Math.random()>>>0),ma=0;
function na(a,b,c){return a.call.apply(a.bind,arguments)}function oa(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?na:oa;return y.apply(m,arguments)}
function pa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var z=Date.now||function(){return+new Date};function A(a,b){function c(){}c.prototype=b.prototype;a.ra=b.prototype;a.prototype=new c;a.prototype.constructor=a}Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return y.apply(m,c)}return y(this,a)};function qa(a){Error.captureStackTrace?Error.captureStackTrace(this,qa):this.stack=Error().stack||"";a&&(this.message=String(a))}A(qa,Error);qa.prototype.name="CustomError";function ra(a,b){return 0==a.lastIndexOf(b,0)}function sa(a,b){return-1!=a.indexOf(b)}Math.random();var ta=Array.prototype,ua=ta.indexOf?function(a,b,c){return ta.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return x(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=ta.forEach?function(a,b,c){ta.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},wa=ta.filter?function(a,b,c){return ta.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,
l=x(a)?a.split(""):a,n=0;n<d;n++)if(n in l){var q=l[n];b.call(c,q,n,a)&&(e[g++]=q)}return e},xa=ta.map?function(a,b,c){return ta.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=x(a)?a.split(""):a,l=0;l<d;l++)l in g&&(e[l]=b.call(c,g[l],l,a));return e},ya=ta.reduce?function(a,b,c,d){d&&(b=y(b,d));return ta.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;va(a,function(c,l){e=b.call(d,e,c,l,a)});return e},za=ta.some?function(a,b,c){return ta.some.call(a,b,c)}:function(a,b,c){for(var d=
a.length,e=x(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return k;return p},Aa=ta.every?function(a,b,c){return ta.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&!b.call(c,e[g],g,a))return p;return k};function Ba(a,b){return 0<=ua(a,b)}function Ca(a){return 0==a.length}function Da(a,b){Ba(a,b)||a.push(b)}function Ea(a,b){var c=ua(a,b),d;(d=0<=c)&&Fa(a,c);return d}function Fa(a,b){ta.splice.call(a,b,1)}
function Ga(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ha(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(ga(d)||(e=ha(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var g=a.length,l=d.length,n=0;n<l;n++)a[g+n]=d[n];else a.push(d)}}
function Ia(a,b){for(var c=b||a,d={},e=0,g=0;g<a.length;){var l=a[g++],n=ja(l)?"o"+ka(l):(typeof l).charAt(0)+l;Object.prototype.hasOwnProperty.call(d,n)||(d[n]=k,c[e++]=l)}c.length=e};function Ja(a){return function(){return a}}var Ka=Ja(p),La=Ja(k),Ma=Ja(m);function Na(a){return function(){f(Error(a))}}function Oa(a){return function(){f(a)}};var Pa="StopIteration"in t?t.StopIteration:Error("StopIteration");var Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za;function $a(){return t.navigator?t.navigator.userAgent:m}function ab(){return t.navigator}Ta=Sa=Ra=Qa=p;var bb;if(bb=$a()){var cb=ab();Qa=ra(bb,"Opera");Ra=!Qa&&(sa(bb,"MSIE")||sa(bb,"Trident"));Sa=!Qa&&sa(bb,"WebKit");Ta=!Qa&&!Sa&&!Ra&&"Gecko"==cb.product}var db=Qa,B=Ra,eb=Ta,fb=Sa,hb=ab(),ib=hb&&hb.platform||"";Ua=sa(ib,"Mac");Va=sa(ib,"Win");Wa=sa(ib,"Linux");Xa=!!ab()&&sa(ab().appVersion||"","X11");var jb=$a();Ya=!!jb&&sa(jb,"Android");Za=!!jb&&sa(jb,"iPhone");
var kb=!!jb&&sa(jb,"iPad");function lb(){var a=t.document;return a?a.documentMode:h}var mb;t:{var nb="",ob;if(db&&t.opera)var pb=t.opera.version,nb="function"==typeof pb?pb():pb;else if(eb?ob=/rv\:([^\);]+)(\)|;)/:B?ob=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:fb&&(ob=/WebKit\/(\S+)/),ob)var qb=ob.exec($a()),nb=qb?qb[1]:"";if(B){var rb=lb();if(rb>parseFloat(nb)){mb=String(rb);break t}}mb=nb}var sb=mb,tb=t.document,ub=tb&&B?lb()||("CSS1Compat"==tb.compatMode?parseInt(sb,10):5):h;function C(){}C.prototype.Mh=p;C.prototype.isDisposed=function(){return this.Mh};C.prototype.Ga=ba(51);C.prototype.xa=ba(3);/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function vb(a,b){this.$=[];this.ya=a;this.wa=b||m;this.q=this.qe=p;this.o=h;this.ka=this.sU=this.ha=p;this.aa=0;this.l=m;this.r=0}s=vb.prototype;s.cancel=ba(52);s.yG=function(a,b){this.ha=p;wb(this,a,b)};function wb(a,b,c){a.qe=k;a.o=c;a.q=!b;xb(a)}function yb(a){a.qe&&(a.ka||f(new zb),a.ka=p)}s.Ac=function(a){yb(this);wb(this,k,a)};s.Mg=ba(18);s.addCallback=ba(41);function Ab(a,b,c,d){a.$.push([b,c,d]);a.qe&&xb(a);return a}s.yx=ba(45);s.wu=function(a){return a instanceof Error};
function Bb(a){return za(a.$,function(a){return ia(a[1])})}function xb(a){a.aa&&a.qe&&Bb(a)&&(t.clearTimeout(a.aa),delete a.aa);a.l&&(a.l.r--,delete a.l);for(var b=a.o,c=p,d=p;a.$.length&&!a.ha;){var e=a.$.shift(),g=e[0],l=e[1],e=e[2];if(g=a.q?l:g)try{var n=g.call(e||a.wa,b);v(n)&&(a.q=a.q&&(n==b||a.wu(n)),a.o=b=n);b instanceof vb&&(d=k,a.ha=k)}catch(q){b=q,a.q=k,Bb(a)||(c=k)}}a.o=b;d&&(Ab(b,y(a.yG,a,k),y(a.yG,a,p)),b.sU=k);c&&(a.aa=t.setTimeout(Oa(b),0))}function zb(){qa.call(this)}A(zb,qa);
zb.prototype.message="Deferred has already fired";zb.prototype.name="AlreadyCalledError";function Cb(){}A(Cb,C);Cb.prototype.kc=function(){};var Db=[],Eb=[],Fb=p;function Gb(a){Db[Db.length]=a;if(Fb)for(var b=0;b<Eb.length;b++)a(y(Eb[b].o,Eb[b]))};function Hb(a,b){this.l=a;this.eb=b}Hb.prototype.execute=function(a){this.l&&(this.l.call(this.eb||m,a),this.l=this.eb=m)};Gb(function(a){Hb.prototype.execute=a(Hb.prototype.execute)});function Ib(a,b){this.RG=a;this.Za=b;this.o=[];this.l=[];this.q=[]}A(Ib,C);s=Ib.prototype;s.jB=Cb;s.kB=m;s.getId=function(){return this.Za};s.Nq=ba(54);s.Ml=function(){return!!this.kB};function Jb(a,b){var c=new a.jB;c.kc(b());a.kB=c;c=(c=!!Kb(a.q,b()))||!!Kb(a.o,b());c||(a.l.length=0);return c}s.Fq=function(a){(a=Kb(this.l,a))&&window.setTimeout(Na("Module errback failures: "+a),0);this.q.length=0;this.o.length=0};
function Kb(a,b){for(var c=[],d=0;d<a.length;d++)try{a[d].execute(b)}catch(e){c.push(e)}a.length=0;return c.length?c:m}s.xa=ba(2);function Lb(){this.Ef={};this.q=[];this.o=[];this.ha=[];this.l=[];this.aa=[];this.wa={};this.r=this.ka=new Ib([],"");this.ya=m;this.$=new vb}A(Lb,C);ea(Lb);s=Lb.prototype;s.jF=p;s.xX=p;s.cB=m;s.Es=0;s.qK=p;s.mP=p;s.JK=m;s.yN=ba(55);s.ZH=function(){return this.JK};s.fc=function(){return 0<this.q.length};function Mb(a){var b=a.qK,c=a.fc();c!=b&&(Nb(a,c?"active":"idle"),a.qK=c);b=0<a.aa.length;b!=a.mP&&(Nb(a,b?"userActive":"userIdle"),a.mP=b)}
s.Lu=function(a,b,c){b||(this.Es=0);this.q=b=Ob(this,a);this.jF?this.o=a:this.o=Ga(b);Mb(this);Ca(b)||(this.ha.push.apply(this.ha,b),a=y(this.cB.bfa,this.cB,Ga(b),this.Ef,m,y(this.X0,this,this.o,b),y(this.Y0,this),!!c),(c=5E3*Math.pow(this.Es,2))?window.setTimeout(a,c):a())};
function Ob(a,b){for(var c=0;c<b.length;c++)a.Ef[b[c]].Ml()&&f(Error("Module already loaded: "+b[c]));for(var d=[],c=0;c<b.length;c++)d=d.concat(Pb(a,b[c]));Ia(d);return!a.jF&&1<d.length?(c=d.shift(),a.l=xa(d,function(a){return[a]}).concat(a.l),[c]):d}function Pb(a,b){var c=[];Ba(a.ha,b)||c.push(b);for(var d=Ga(a.Ef[b].RG);d.length;){var e=d.pop();a.Ef[e].Ml()||Ba(a.ha,e)||(c.unshift(e),Array.prototype.unshift.apply(d,a.Ef[e].RG))}Ia(c);return c}
function Qb(a){a.r==a.ka&&(a.r=m,Jb(a.ka,y(a.ZH,a))&&Rb(a,4),Mb(a))}function Sb(a){var b=Lb.Xb();b.isDisposed()||(Jb(b.Ef[a],y(b.ZH,b))&&Rb(b,4),Ea(b.aa,a),Ea(b.q,a),Ca(b.q)&&Tb(b),b.ya&&a==b.ya&&(b.$.qe||b.$.Ac()),Mb(b))}s.load=ba(8);function Ub(a){var b=Lb.Xb();b.r=b.Ef[a]}function Vb(){var a=Lb.Xb();a.r&&a.r.getId();a.r=m}
s.X0=function(a,b,c){this.Es++;this.o=a;va(b,pa(Ea,this.ha),this);401==c?(Rb(this,0),this.l.length=0):410==c?(Wb(this,3),Tb(this)):3<=this.Es?(Wb(this,1),Tb(this)):this.Lu(this.o,k,8001==c)};s.Y0=function(){Wb(this,2);Tb(this)};function Wb(a,b){1<a.o.length?a.l=xa(a.o,function(a){return[a]}).concat(a.l):Rb(a,b)}
function Rb(a,b){var c=a.o;a.q.length=0;for(var d=[],e=0;e<a.l.length;e++){var g=wa(a.l[e],function(a){var b=Pb(this,a);return za(c,function(a){return Ba(b,a)})},a);Ha(d,g)}for(e=0;e<c.length;e++)Da(d,c[e]);for(e=0;e<d.length;e++){for(g=0;g<a.l.length;g++)Ea(a.l[g],d[e]);Ea(a.aa,d[e])}var l=a.wa.error;if(l)for(e=0;e<l.length;e++)for(var n=l[e],g=0;g<d.length;g++)n("error",d[g],b);for(e=0;e<c.length;e++)a.Ef[c[e]]&&a.Ef[c[e]].Fq(b);a.o.length=0;Mb(a)}
function Tb(a){for(;a.l.length;){var b=wa(a.l.shift(),function(a){return!this.Ef[a].Ml()},a);if(0<b.length){a.Lu(b);return}}Mb(a)}s.Nq=ba(53);function Nb(a,b){for(var c=a.wa[b],d=0;c&&d<c.length;d++)c[d](b)}s.xa=ba(1);


Lb.prototype.yN=ca(55,function(a,b){if(x(a)){for(var c=a.split("/"),d=[],e=0;e<c.length;e++){var g=c[e].split(":"),l=g[0];if(g[1])for(var g=g[1].split(","),n=0;n<g.length;n++)g[n]=d[parseInt(g[n],36)];else g=[];d.push(l);this.Ef[l]=new Ib(g,l)}b&&b.length?(Ha(this.q,b),this.ya=b[b.length-1]):this.$.qe||this.$.Ac();Qb(this)}});var _ModuleManager_initialize=y(Lb.prototype.yN,Lb.Xb());
_ModuleManager_initialize("sy3/full:0/lite:0/r",['sy3','lite']);
}catch(e){_DumpException(e)}
try{
function Xb(a,b,c){b=new Hb(b,c);a.push(b);return b}function Zb(a,b){Ba(a.aa,b)||a.aa.push(b)}function $b(a,b){if(Ba(a.q,b))return k;for(var c=0;c<a.l.length;c++)if(Ba(a.l[c],b))return k;return p}function ac(a,b){Xb(a.l,b,h)}function bc(a,b,c,d,e){c.Nq(e.Ac,e);ac(c,function(a){e.Mg(Error(a))});$b(a,b)?d&&(Zb(a,b),Mb(a)):d&&Zb(a,b)}function E(a){a&&"function"==typeof a.Ga&&a.Ga()}
function cc(a,b,c){var d=[];Ia(b,d);b=[];for(var e={},g=0;g<d.length;g++){var l=d[g],n=a.Ef[l],q=new vb;e[l]=q;n.Ml()?q.Ac(a.JK):(bc(a,l,n,!!c,q),$b(a,l)||b.push(l))}0<b.length&&(a.xX?a.$.addCallback(y(a.Lu,a,b)):Ca(a.q)?a.Lu(b):(a.l.push(b),Mb(a)));return e}function dc(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ha(d)?dc.apply(m,d):E(d)}}function ec(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}Ib.prototype.Nq=ca(54,function(a,b){return Xb(this.o,a,b)});
Lb.prototype.Nq=ca(53,function(a,b){ga(a)||(a=[a]);for(var c=0;c<a.length;c++){var d=a[c],e=b,g=this.wa;g[d]||(g[d]=[]);g[d].push(e)}});C.prototype.Ga=ca(51,function(){this.Mh||(this.Mh=k,this.xa())});vb.prototype.addCallback=ca(41,function(a,b){return Ab(this,a,m,b)});vb.prototype.Mg=ca(18,function(a){yb(this);wb(this,p,a)});Lb.prototype.load=ca(8,function(a,b){return cc(this,[a],b)[a]});C.prototype.xa=ca(3,function(){if(this.Di)for(;this.Di.length;)this.Di.shift()()});
Ib.prototype.xa=ca(2,function(){Ib.ra.xa.call(this);E(this.kB)});Lb.prototype.xa=ca(1,function(){Lb.ra.xa.call(this);dc(ec(this.Ef),this.ka);this.wa=this.l=this.aa=this.o=this.q=this.Ef=m});function fc(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function gc(){}gc.prototype.next=function(){f(Pa)};gc.prototype.hh=function(){return this};function hc(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}var ic={};
function jc(a){if("function"==typeof a.Ib)return a.Ib();if("function"!=typeof a.nb){if(ha(a)||x(a)){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return fc(a)}}function kc(a){if("function"==typeof a.nb)return a.nb();if(x(a))return a.split("");if(ha(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ec(a)}function lc(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
function nc(a,b){for(var c=0,d=hc(String(a)).split("."),e=hc(String(b)).split("."),g=Math.max(d.length,e.length),l=0;0==c&&l<g;l++){var n=d[l]||"",q=e[l]||"",r=RegExp("(\\d*)(\\D*)","g"),u=RegExp("(\\d*)(\\D*)","g");do{var w=r.exec(n)||["","",""],D=u.exec(q)||["","",""];if(0==w[0].length&&0==D[0].length)break;c=((0==w[1].length?0:parseInt(w[1],10))<(0==D[1].length?0:parseInt(D[1],10))?-1:(0==w[1].length?0:parseInt(w[1],10))>(0==D[1].length?0:parseInt(D[1],10))?1:0)||((0==w[2].length)<(0==D[2].length)?
-1:(0==w[2].length)>(0==D[2].length)?1:0)||(w[2]<D[2]?-1:w[2]>D[2]?1:0)}while(0==c)}return c}var oc=/[&<>\"]/,pc=/\"/g,qc=/>/g,rc=/</g,sc=/&/g;function tc(a){return ic[a]||(ic[a]=0<=nc(sb,a))}function F(a,b){this.Db={};this.l=[];this.r=this.o=0;var c=arguments.length;if(1<c){c%2&&f(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.wn(a)}s=F.prototype;s.Fb=ba(5);
s.nb=function(){uc(this);for(var a=[],b=0;b<this.l.length;b++)a.push(this.Db[this.l[b]]);return a};s.Ib=function(){uc(this);return this.l.concat()};function vc(a,b){return lc(a.Db,b)}s.Qi=ba(57);s.equals=ba(49);s.isEmpty=ba(13);s.clear=ba(62);s.remove=function(a){return lc(this.Db,a)?(delete this.Db[a],this.o--,this.r++,this.l.length>2*this.o&&uc(this),k):p};
function uc(a){if(a.o!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];lc(a.Db,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.o!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],lc(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}s.get=function(a,b){return lc(this.Db,a)?this.Db[a]:b};s.set=function(a,b){lc(this.Db,a)||(this.o++,this.l.push(a),this.r++);this.Db[a]=b};s.wn=function(a){var b;a instanceof F?(b=a.Ib(),a=a.nb()):(b=fc(a),a=ec(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};s.Vb=function(){return new F(this)};
s.hh=function(a){uc(this);var b=0,c=this.l,d=this.Db,e=this.r,g=this,l=new gc;l.next=function(){for(;;){e!=g.r&&f(Error("The map has changed since the iterator was created"));b>=c.length&&f(Pa);var l=c[b++];return a?l:d[l]}};return l};var wc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function xc(a,b){return Array(b+1).join(a)}
function yc(a){if(!oc.test(a))return a;-1!=a.indexOf("\x26")&&(a=a.replace(sc,"\x26amp;"));-1!=a.indexOf("\x3c")&&(a=a.replace(rc,"\x26lt;"));-1!=a.indexOf("\x3e")&&(a=a.replace(qc,"\x26gt;"));-1!=a.indexOf('"')&&(a=a.replace(pc,"\x26quot;"));return a}function zc(a,b,c){a=a.split(".");c=c||t;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||b===h?c=c[d]?c[d]:c[d]={}:c[d]=b}function Ac(a){return B&&ub>=a}
function Bc(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ha(a)||x(a))va(a,b,c);else for(var d=jc(a),e=kc(a),g=e.length,l=0;l<g;l++)b.call(c,e[l],d&&d[l],a)}function Cc(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<wc.length;g++)c=wc[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}function Dc(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ec(a){return ta.concat.apply(ta,arguments)}
function Fc(a){return encodeURIComponent(String(a))}var Gc;Ub("sy3");function Hc(a,b,c){this.q=a;this.l=b||m;this.o=c||[]}Hc.prototype.toString=function(){return this.q};Hc.prototype.getModuleId=ba(50);var Ic=new Hc("b"),Jc=new Hc("c"),Kc=new Hc("d"),Lc=new Hc("e"),Mc=new Hc("f"),Nc=new Hc("h"),Qc=new Hc("k"),Rc=new Hc("l"),Sc=new Hc("t"),Tc=new Hc("z"),Uc=new Hc("A"),Vc=new Hc("G"),Wc=new Hc("M"),Yc=new Hc("N"),Zc=new Hc("X"),$c=new Hc("aa");function ad(a,b){a!=m&&this.yb.apply(this,arguments)}s=ad.prototype;s.$i="";s.set=function(a){this.$i=""+a};s.yb=function(a,b,c){this.$i+=a;if(b!=m)for(var d=1;d<arguments.length;d++)this.$i+=arguments[d];return this};s.clear=ba(61);s.toString=function(){return this.$i};var bd=RegExp("'","g"),cd=RegExp("\\\\27","g");function dd(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}var ed=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function G(){this.l=[]}G.prototype.Ma=ba(37);function H(a,b,c,d,e){b||(b=c?[c]:[]);a.ea=b;a.l=[];if(e)for(b=0;b<e.length;b++)a.ea[e[b]]=a.ea[e[b]]||[];if(-1!=d){a.Xw={};t:{e=a.ea;if(e.length&&(c=e.length-1,(b=e[c])&&"object"==typeof b&&"number"!=typeof b.length)){c<d&&(e[d]=b,delete e[c]);d=b;break t}b={};d=e[Math.max(e.length,d)]=b}a.Ww=d}}function fd(a,b,c,d){a.l[c]||!d&&!a.ea[c]||(a.l[c]=new b(a.ea[c]));return a.l[c]}G.prototype.uc=ba(40);G.prototype.toString=function(){return this.ea.toString()};
function I(a,b){gd[a]=b;b.qi=a}var gd={};var hd=!B||Ac(9),id=!eb&&!B||B&&Ac(9)||eb&&tc("1.9.1"),jd=B&&!tc("9");function K(a){return a?new kd(ld(a)):Gc||(Gc=new kd)}function md(a,b){Dc(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in nd?a.setAttribute(nd[d],b):ra(d,"aria-")||ra(d,"data-")?a.setAttribute(d,b):a[d]=b})}var nd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function od(a,b,c,d){function e(c){c&&b.appendChild(x(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];ha(g)&&!pd(g)?va(qd(g)?Ga(g):g,e):e(g)}}function rd(a,b){od(ld(a),a,arguments,1)}function sd(a){for(var b;b=a.firstChild;)a.removeChild(b)}function td(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function ud(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}function vd(a){return a&&a.parentNode?a.parentNode.removeChild(a):m}
function wd(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}function xd(a){return id&&a.children!=h?a.children:wa(a.childNodes,function(a){return 1==a.nodeType})}function yd(a){return a.firstElementChild!=h?a.firstElementChild:zd(a.firstChild,k)}function zd(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function pd(a){return ja(a)&&0<a.nodeType}
function Ad(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function ld(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Cd(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else sd(a),a.appendChild(ld(a).createTextNode(String(b)))}function Dd(a){if("outerHTML"in a)return a.outerHTML;var b=ld(a).createElement("div");b.appendChild(a.cloneNode(k));return b.innerHTML}var Ed={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Fd={IMG:" ",BR:"\n"};
function Gd(a){if(jd&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Hd(a,b,k);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");jd||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Hd(a,b,c){if(!(a.nodeName in Ed))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Fd)b.push(Fd[a.nodeName]);else for(a=a.firstChild;a;)Hd(a,b,c),a=a.nextSibling}function qd(a){if(a&&"number"==typeof a.length){if(ja(a))return"function"==typeof a.item||"string"==typeof a.item;if(ia(a))return"function"==typeof a.item}return p}function kd(a){this.Ud=a||t.document||document}s=kd.prototype;s.Ia=K;s.tb=ba(15);s.ia=ba(20);s.Pb=kd.prototype.ia;
s.tC=md;s.cb=ba(44);s.createElement=function(a){return this.Ud.createElement(a)};s.appendChild=function(a,b){a.appendChild(b)};s.iI=rd;s.Ct=sd;s.xA=td;s.Y2=ud;s.removeNode=vd;s.q9=wd;s.getChildren=xd;s.VH=yd;s.mK=pd;s.contains=Ad;s.Rv=Cd;s.N_=Gd;var Id=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?\x3d[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Jd(a){if(Kd){Kd=p;var b=t.location;if(b){var c=b.href;c&&(c=(c=Jd(c)[3]||m)&&decodeURIComponent(c))&&c!=b.hostname&&(Kd=k,f(Error()))}}return a.match(Id)}var Kd=fb;function Ld(a){this.l=[];H(this,a,"ci:dc",-1,[])}A(Ld,G);I("ci:dc",Ld);Ld.prototype.Ma=ba(36);function Md(a){this.l=[];H(this,a,"ci:cbb",-1,[36])}A(Md,G);I("ci:cbb",Md);Md.prototype.Ma=ba(35);function Nd(a){this.l=[];H(this,a,"ci:ec",-1,[])}A(Nd,G);I("ci:ec",Nd);Nd.prototype.Ma=ba(34);function Od(a){this.l=[];H(this,a,"ci:cpc",-1,[])}A(Od,G);I("ci:cpc",Od);Od.prototype.Ma=ba(33);function Pd(a){return a.ea[7]!=m?a.ea[7]:""};function Qd(a){this.l=[];H(this,a,"ci:ha:a",-1,[])}A(Qd,G);I("ci:ha:a",Qd);Qd.prototype.Ma=ba(32);function Rd(a){this.l=[];H(this,a,"ci:ha:q",-1,[])}A(Rd,G);I("ci:ha:q",Rd);Rd.prototype.Ma=ba(31);function Td(a){this.l=[];H(this,a,"ci:ha",-1,[])}A(Td,G);I("ci:ha",Td);Td.prototype.Ma=ba(30);function Ud(a){this.l=[];H(this,a,"ci:hpa",-1,[])}A(Ud,G);I("ci:hpa",Ud);Ud.prototype.Ma=ba(29);function Vd(a){this.l=[];H(this,a,"ci:csm",-1,[15])}A(Vd,G);I("ci:csm",Vd);Vd.prototype.Ma=ba(28);function Wd(a){return a.ea[26]!=m?a.ea[26]:p}function Xd(a){return a.ea[28]!=m?a.ea[28]:p}function Yd(a){return a.ea[32]}function Zd(a){return a.ea[33]!=m?a.ea[33]:k}function $d(a){this.l=[];H(this,a,"ci:csmmc",-1,[])}A($d,G);I("ci:csmmc",$d);$d.prototype.Ma=ba(27);function ae(a){this.l=[];H(this,a,"ci:cui:uss",-1,[])}A(ae,G);I("ci:cui:uss",ae);ae.prototype.Ma=ba(26);ae.prototype.getName=function(){return this.ea[2]!=m?this.ea[2]:""};ae.prototype.ic=ba(7);ae.prototype.pd=function(){return this.ea[4]!=m?this.ea[4]:""};function be(a){this.l=[];H(this,a,"ci:cui",-1,[9])}A(be,G);I("ci:cui",be);be.prototype.Ma=ba(25);be.prototype.Pa=function(){return this.ea[1]!=m?this.ea[1]:""};be.prototype.Jb=function(){return this.ea[3]!=m?this.ea[3]:""};function ce(a){return a.ea[7]!=m?a.ea[7]:0};function de(a){this.l=[];H(this,a,"ci:cro",-1,[])}A(de,G);I("ci:cro",de);de.prototype.Ma=ba(24);function ee(a){return fd(a,be,1,1)}function fe(a){return fd(a,Od,2,1)}function ge(a){return fd(a,Vd,3,1)};function he(a){de.call(this,a);this.lj="u";this.Ea=p;this.Gd="";this.wc="channel";this.Um="CLID"+String(Math.random()).substring(2);this.Oc="";this.version="local";this.Ik="WCX";this.$g=-1;this.aa="_GC_roster";this.vj=0;this.Ua=[];this.$e=[];this.Ka=[];this.Qc="";this.hd="Google Talk";this.Mk=this.Lk=this.vd=this.Ya=p;this.bp=k;this.dh=this.nd=this.Oa=this.Ta=p;this.startTime=0;this.La=p;this.Jk="";this.Di=this.Fd=this.ap=p;this.Mi="";this.xj=k;this.locale="de";this.Wf=this.Wq=this.rj=p;this.vh=k;
this.Mh=this.Bh=this.gj=this.$=this.Va=this.ha=p;this.Tb=m;this.Ok=k;this.Ca=this.Pk=p;this.Oe=1073741824;this.Ad=Infinity;this.cp=this.he=this.jd=this.zb=this.Ba=this.nj=this.o=this.q=p;this.ya=k;this.Fa=-1;this.Qd=1;this.hb=p;this.Nk=this.r="";this.ig=m;this.Ub=k;this.Kk=this.Td=this.ka=this.Pd=this.yj=this.od=this.ef=this.Nb=p;this.Ah=m;this.sj=this.Bi=this.Dc=this.$c=this.wj=this.Df=p;this.Ir=[];v(Pd(fe(this)))||(fe(this).ea[7]="");this.wa=p;this.Rd=m;this.Hk=this.Gk=0}A(he,de);
he.prototype.register=ba(59);
zc("GoogleChat_GetConfig",function(a,b,c,d,e,g,l,n,q,r,u,w,D,N,M,J,gb,Oc,Bd,Xc,Te,Sd,Af,bg,Ue,qe,mc,Pc,gh,Yb,Mm,re,ik,Nm,cg,jk,kk,bG,dx,cG,dG,s9,t9,u9,v9,w9,x9,y9,z9,A9,B9,C9,D9,E9,F9,G9,H9,I9,J9,K9,L9,M9,N9,O9,P9,Q9,R9,S9,T9,U9,V9,W9,X9,uR,Y9,Z9,T){T&&(T=dd(T));T=new he(T);T.Ea=k;T.Gd=a;T.wc=b;T.Um=c;T.lj=d;T.Oc=e;T.version=g;T.Ik=l;T.$g=n;T.aa=q;T.vj=r;T.Ua=u;T.$e=w;T.Ka=D;T.Qc=N;T.hd=M;T.Ya="aquasar"==M||"Google-Voice"==M;T.vd="hangout_lite"==M||"hangout"==M;T.Lk="gvc"==M;T.q="ChromeOS"==M;T.o=
"aChromeExtension"==M;T.nj="gmail"==M;T.Mk="present"==M;T.bp=J;T.Ta=gb;T.Oa=Oc;T.nd=Bd;T.dh=Xc;T.startTime=Te;T.La=Sd;T.Jk=Af;T.ap=bg;T.Fd=Ue;T.Di=qe;T.Mi=mc;T.xj=Pc;T.locale=gh;T.rj=Yb;T.Wq=Mm;T.Wf=re;T.vh=ik;T.ha=Nm;T.Va=cg;T.$=jk;T.gj=kk;T.Bh=bG;T.Mh=dx;T.Tb=cG;T.Pk=dG;T.Ok=s9;T.Ca=t9;T.Oe=u9;T.Ad=v9;T.Ba=w9;T.zb=x9;T.jd=y9;T.he=z9;T.cp=A9;T.ya=B9;T.Fa=C9;T.Qd=D9;T.hb=E9;T.r=F9;T.Nk=G9;T.ig=H9;T.Ub=I9;T.Nb=J9;T.ef=K9;T.od=L9;T.yj=M9;T.Pd=N9;T.ka=O9;T.Td=P9;T.Kk=Q9;T.Ah=R9;T.Df=S9;T.wj=T9;T.$c=
U9;T.Dc=V9;T.Bi=W9;T.sj=X9;T.wa=Ue||!Yd(ge(T));uR&&(T.Rd=new Ld(dd(uR)));T.Gk=Y9||0;T.Hk=Z9||0;switch(M){case "docs":T.wa=p}return T},h);function L(a,b){var c;a instanceof L?(this.Bl=v(b)?b:a.Bl,ie(this,a.qg),je(this,a.Uo),ke(this,a.dc()),le(this,a.xi),me(this,a.Cf),ne(this,a.l.Vb()),oe(this,a.Xi)):a&&(c=Jd(String(a)))?(this.Bl=!!b,ie(this,c[1]||"",k),je(this,c[2]||"",k),ke(this,c[3]||"",k),le(this,c[4]),me(this,c[5]||"",k),ne(this,c[6]||"",k),oe(this,c[7]||"",k)):(this.Bl=!!b,this.l=new pe(m,0,this.Bl))}s=L.prototype;s.qg="";s.Uo="";s.Al="";s.xi=m;s.Cf="";s.Xi="";s.K_=p;s.Bl=p;
s.toString=function(){var a=[],b=this.qg;b&&a.push(se(b,te),":");if(b=this.dc()){a.push("//");var c=this.Uo;c&&a.push(se(c,te),"@");a.push(Fc(b));b=this.xi;b!=m&&a.push(":",String(b))}if(b=this.Cf)this.Al&&"/"!=b.charAt(0)&&a.push("/"),a.push(se(b,"/"==b.charAt(0)?ue:ve));(b=this.l.toString())&&a.push("?",b);(b=this.Xi)&&a.push("#",se(b,we));return a.join("")};s.Vb=function(){return new L(this)};
function ie(a,b,c){xe(a);a.qg=c?b?decodeURIComponent(b):"":b;a.qg&&(a.qg=a.qg.replace(/:$/,""));return a}function je(a,b,c){xe(a);a.Uo=c?b?decodeURIComponent(b):"":b}s.dc=function(){return this.Al};function ke(a,b,c){xe(a);a.Al=c?b?decodeURIComponent(b):"":b;return a}function le(a,b){xe(a);b?(b=Number(b),(isNaN(b)||0>b)&&f(Error("Bad port number "+b)),a.xi=b):a.xi=m}function me(a,b,c){xe(a);a.Cf=c?b?decodeURIComponent(b):"":b;return a}
function ne(a,b,c){xe(a);b instanceof pe?(a.l=b,ye(a.l,a.Bl)):(c||(b=se(b,ze)),a.l=new pe(b,0,a.Bl))}s.pb=ba(38);function oe(a,b,c){xe(a);a.Xi=c?b?decodeURIComponent(b):"":b}function xe(a){a.K_&&f(Error("Tried to modify a read-only Uri"))}function Ae(a,b){return a instanceof L?a.Vb():new L(a,b)}function se(a,b){return x(a)?encodeURI(a).replace(b,Be):m}function Be(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}
var te=/[#\/\?@]/g,ve=/[\#\?:]/g,ue=/[\#\?]/g,ze=/[\#\?@]/g,we=/#/g;function pe(a,b,c){this.l=a||m;this.o=!!c}function Ce(a){if(!a.Xd&&(a.Xd=new F,a.Qf=0,a.l))for(var b=a.l.split("\x26"),c=0;c<b.length;c++){var d=b[c].indexOf("\x3d"),e=m,g=m;0<=d?(e=b[c].substring(0,d),g=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=De(a,e);a.add(e,g?decodeURIComponent(g.replace(/\+/g," ")):"")}}s=pe.prototype;s.Xd=m;s.Qf=m;s.Fb=ba(4);
s.add=function(a,b){Ce(this);this.l=m;a=De(this,a);var c=this.Xd.get(a);c||this.Xd.set(a,c=[]);c.push(b);this.Qf++;return this};s.remove=function(a){Ce(this);a=De(this,a);return vc(this.Xd,a)?(this.l=m,this.Qf-=this.Xd.get(a).length,this.Xd.remove(a)):p};s.clear=ba(60);s.isEmpty=ba(11);function Ee(a,b){Ce(a);b=De(a,b);return vc(a.Xd,b)}s.Qi=ba(56);s.Ib=function(){Ce(this);for(var a=this.Xd.nb(),b=this.Xd.Ib(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
s.nb=function(a){Ce(this);var b=[];if(x(a))Ee(this,a)&&(b=Ec(b,this.Xd.get(De(this,a))));else{a=this.Xd.nb();for(var c=0;c<a.length;c++)b=Ec(b,a[c])}return b};s.set=function(a,b){Ce(this);this.l=m;a=De(this,a);Ee(this,a)&&(this.Qf-=this.Xd.get(a).length);this.Xd.set(a,[b]);this.Qf++;return this};s.get=function(a,b){var c=a?this.nb(a):[];return 0<c.length?String(c[0]):b};function Fe(a,b,c){a.remove(b);0<c.length&&(a.l=m,a.Xd.set(De(a,b),Ga(c)),a.Qf+=c.length)}
s.toString=function(){if(this.l)return this.l;if(!this.Xd)return"";for(var a=[],b=this.Xd.Ib(),c=0;c<b.length;c++)for(var d=b[c],e=Fc(d),d=this.nb(d),g=0;g<d.length;g++){var l=e;""!==d[g]&&(l+="\x3d"+Fc(d[g]));a.push(l)}return this.l=a.join("\x26")};s.Vb=function(){var a=new pe;a.l=this.l;this.Xd&&(a.Xd=this.Xd.Vb(),a.Qf=this.Qf);return a};function De(a,b){var c=String(b);a.o&&(c=c.toLowerCase());return c}
function ye(a,b){b&&!a.o&&(Ce(a),a.l=m,Bc(a.Xd,function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Fe(this,e,a))},a));a.o=b}s.xz=ba(47);var Ge=/<[^>]*>|&[^;]+;/g;function He(a,b){return b?a.replace(Ge,""):a}
var Ie=RegExp("[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]"),Je=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]"),Ke=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]"),Le=/^http:\/\/.*/,Me=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff][^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*$"),Ne=
RegExp("[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc][^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*$"),Oe=/\s+/,Pe=/\d/;function Qe(a,b){for(var c=0,d=0,e=p,g=He(a,b).split(Oe),l=0;l<g.length;l++){var n=g[l];Ke.test(He(n,h))?(c++,d++):Le.test(n)?e=k:Je.test(He(n,h))?d++:Pe.test(n)&&(e=k)}return 0==d?e?1:0:0.4<c/d?-1:1};function Re(a,b){this.l="number"==typeof a?0<a?1:0>a?-1:m:a==m?m:a?-1:1;this.o=!!b}Re.prototype.q=Qe;var Se;function Ve(a,b,c){ha(c)&&(c=c.join(" "));var d="aria-"+b;""===c||c==h?(Se||(Se={atomic:p,autocomplete:"none",dropeffect:"none",haspopup:p,live:"off",multiline:p,multiselectable:p,orientation:"vertical",readonly:p,relevant:"additions text",required:p,sort:"none",busy:p,disabled:p,hidden:p,invalid:"false"}),c=Se,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)};var We={"":1,n:Math.pow(1024,-3),u:Math.pow(1024,-2),m:1/1024,k:1024,K:1024,M:Math.pow(1024,2),G:Math.pow(1024,3),T:Math.pow(1024,4),P:Math.pow(1024,5)},Xe=B&&tc(8),Ye=fb?"\x3cwbr\x3e\x3c/wbr\x3e":db?"\x26shy;":Xe?"\x26#8203;":"\x3cwbr\x3e";var Ze={},$e={},af={},bf={},cf={};function df(){f(Error("Do not instantiate directly"))}df.prototype.Hj=m;df.prototype.toString=function(){return this.content};function ef(a,b){return a!=m&&a.Rh===b}function ff(a){if(a!=m)switch(a.Hj){case 1:return 1;case -1:return-1;case 0:return 0}return m}function gf(){df.call(this)}A(gf,df);gf.prototype.Rh=Ze;function hf(){df.call(this)}A(hf,df);hf.prototype.Rh={};hf.prototype.Hj=1;function jf(){df.call(this)}A(jf,df);jf.prototype.Rh={};function kf(){df.call(this)}A(kf,df);kf.prototype.Rh=$e;kf.prototype.Hj=1;function lf(){df.call(this)}A(lf,df);lf.prototype.Rh=af;lf.prototype.Hj=1;function mf(){df.call(this)}A(mf,df);
mf.prototype.Rh=bf;mf.prototype.Hj=1;function nf(a,b){this.content=String(a);this.Hj=b!=m?b:m}A(nf,df);nf.prototype.Rh=cf;function of(a){function b(){}b.prototype=a.prototype;return function(a,d){var e=new b;e.content=String(a);d!==h&&(e.Hj=d);return e}}function pf(a){function b(){}b.prototype=a.prototype;return function(a){var d=new b;d.content=String(a);return d}}var qf=of(gf);pf(hf);of(jf);pf(kf);var rf=pf(lf);pf(mf);
(function(a){function b(){}b.prototype=a.prototype;return function(a,d){if(!String(a))return"";var e=new b;e.content=String(a);d!==h&&(e.Hj=d);return e}})(gf);function O(a){return a!=m&&a.Rh===Ze?a.content:String(a).replace(sf,tf)}function uf(a){return ef(a,cf)?"zSoyz":String(a)}var vf={};function wf(a){var b=vf[1]||(vf[1]=new Re(1)),c=ff(a);c==m&&(c=Qe(a+"",ef(a,Ze)));return rf(c!=b.l?-1==c?'dir\x3d"rtl"':1==c?'dir\x3d"ltr"':"":"")}
var xf={"\x00":"\x26#0;",'"':"\x26quot;","\x26":"\x26amp;","'":"\x26#39;","\x3c":"\x26lt;","\x3e":"\x26gt;","\t":"\x26#9;","\n":"\x26#10;","\x0B":"\x26#11;","\f":"\x26#12;","\r":"\x26#13;"," ":"\x26#32;","-":"\x26#45;","/":"\x26#47;","\x3d":"\x26#61;","`":"\x26#96;","\u0085":"\x26#133;","\u00a0":"\x26#160;","\u2028":"\x26#8232;","\u2029":"\x26#8233;"};function tf(a){return xf[a]}var sf=/[\x00\x22\x26\x27\x3c\x3e]/g;function yf(a){this.l=[];H(this,a,"ru",-1,[15])}A(yf,G);I("ru",yf);s=yf.prototype;s.Ma=ba(23);s.Pa=function(){return this.ea[1]};s.Jb=function(){return this.ea[18]};s.ic=ba(6);s.Ce=ba(46);s.vk=ba(14);s.Rg=function(){return this.ea[12]};s.yl=ba(39);s.wl=function(){return this.ea[21]};function zf(a){this.l=[];H(this,a,"vc",-1,[])}A(zf,G);I("vc",zf);zf.prototype.Ma=ba(22);zf.prototype.Pa=function(){return this.ea[1]};zf.prototype.getName=function(){return this.ea[2]};function Bf(a){this.l=[];H(this,a,"p",-1,[])}A(Bf,G);I("p",Bf);s=Bf.prototype;s.Ma=ba(21);s.Pa=function(){return this.ea[1]};s.Ec=function(){return this.ea[3]};s.getStatus=function(){return this.ea[4]};s.Xe=function(){return this.ea[6]};var Cf={s:function(a,b,c){return isNaN(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+xc(" ",c-a.length):xc(" ",c-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=a.toFixed(e));var g;g=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=g+d);if(isNaN(c)||d.length>=c)return d;d=isNaN(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=c-d.length-g.length;return d=0<=b.indexOf("-",0)?g+d+xc(" ",a):g+xc(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,g,l,n){return Cf.f(parseInt(a,
10),b,c,d,0,g,l,n)}};Cf.i=Cf.d;Cf.u=Cf.d;function Df(a){this.l=[];H(this,a,"",-1,[])}A(Df,G);s=Df.prototype;s.fd=function(){return this.ea[0]};s.NM=function(a){this.ea[0]=a};s.YB=function(){return this.ea[11]};s.RM=function(a){this.ea[11]=a};s.getHeight=function(){return this.ea[12]};s.HM=function(a){this.ea[12]=a};s.B_=function(){return this.ea[32]};s.W8=function(a){this.ea[32]=a};s.QH=function(){return this.ea[1]!=m?this.ea[1]:p};s.EM=function(a){this.ea[1]=a};s.g_=function(){return this.ea[31]};s.M8=function(a){this.ea[31]=a};
s.cI=function(){return this.ea[18]!=m?this.ea[18]:p};s.QM=function(a){this.ea[18]=a};s.$y=function(){return this.ea[19]!=m?this.ea[19]:p};s.ZB=function(a){this.ea[19]=a};s.YZ=function(){return this.ea[2]!=m?this.ea[2]:p};s.G8=function(a){this.ea[2]=a};s.C8=function(){return this.ea[3]!=m?this.ea[3]:p};s.L8=function(a){this.ea[3]=a};s.D_=function(){return this.ea[8]};s.p$=function(a){this.ea[8]=a};s.E_=function(){return this.ea[9]};s.q$=function(a){this.ea[9]=a};s.F_=function(){return this.ea[10]};
s.r$=function(a){this.ea[10]=a};s.C_=function(){return this.ea[13]!=m?this.ea[13]:p};s.o$=function(a){this.ea[13]=a};s.d_=function(){return this.ea[33]!=m?this.ea[33]:p};s.J8=function(a){this.ea[33]=a};s.a_=function(){return this.ea[14]};s.I8=function(a){this.ea[14]=a};s.h_=function(){return this.ea[15]};s.N8=function(a){this.ea[15]=a};s.YH=function(){return this.ea[16]};s.LM=function(a){this.ea[16]=a};s.eI=function(){return this.ea[17]};s.s$=function(a){this.ea[17]=a};s.fI=function(){return this.ea[44]};
s.t$=function(a){this.ea[44]=a};s.i_=function(){return this.ea[21]};s.d$=function(a){this.ea[21]=a};s.ZZ=function(){return this.ea[20]};s.H8=function(a){this.ea[20]=a};s.$Z=function(){return this.ea[24]};s.a$=function(a){this.ea[24]=a};s.XZ=function(){return this.ea[22]!=m?this.ea[22]:p};s.W9=function(a){this.ea[22]=a};s.D8=function(){return this.ea[23]};s.X8=function(a){this.ea[23]=a};s.H_=function(){return this.ea[35]};s.u$=function(a){this.ea[35]=a};
s.z_=function(){return this.ea[5]!=m?this.ea[5]:p};s.l$=function(a){this.ea[5]=a};s.y_=function(){return this.ea[25]};s.k$=function(a){this.ea[25]=a};s.f_=function(){return this.ea[29]};s.K8=function(a){this.ea[29]=a};s.I_=function(){return this.ea[30]};s.Y8=function(a){this.ea[30]=a};s.r_=function(){return this.ea[26]};s.S8=function(a){this.ea[26]=a};s.u_=function(){return this.ea[27]};s.j$=function(a){this.ea[27]=a};s.w_=function(){return this.ea[34]!=m?this.ea[34]:p};
s.U8=function(a){this.ea[34]=a};s.x_=function(){return this.ea[40]!=m?this.ea[40]:p};s.V8=function(a){this.ea[40]=a};s.o_=function(){return this.ea[47]!=m?this.ea[47]:p};s.R8=function(a){this.ea[47]=a};s.v_=function(){return this.ea[48]!=m?this.ea[48]:p};s.T8=function(a){this.ea[48]=a};s.l_=function(){return this.ea[36]!=m?this.ea[36]:p};s.O8=function(a){this.ea[36]=a};s.VZ=function(){return this.ea[37]};s.V9=function(a){this.ea[37]=a};s.B8=function(){return this.ea[38]};
s.E8=function(a){this.ea[38]=a};s.m_=function(){return this.ea[39]};s.P8=function(a){this.ea[39]=a};s.c_=function(){return this.ea[41]};s.c$=function(a){this.ea[41]=a};s.b_=function(){return this.ea[42]};s.b$=function(a){this.ea[42]=a};s.t_=function(){return this.ea[43]};s.i$=function(a){this.ea[43]=a};s.n_=function(){return this.ea[45]};s.Q8=function(a){this.ea[45]=a};function P(){Df.call(this)}A(P,Df);P.prototype.ha=function(a){this.q=a};P.prototype.$=function(){return this.q};P.prototype.aa=function(a){this.o=a};P.prototype.r=function(){return this.o};function Ef(){}s=Ef.prototype;
s.parse=function(a){var b=new P,c=new P;if(""==a)a=k;else{a=a.split("-");for(var d=k,e=0;e<a.length;e++){var g=a[e],l=g.substring(0,1);if("O"==l||"J"==l){for(l="";12>l.length&&e<a.length;)g=a[e],l=l+"-"+g,e++;g=l.substring(1)}var n=b,q=c;if(0==g.length)g=p;else{var r=h,l=g.substring(0,1),r=g.substring(1);if("f"==l.toLowerCase()&&("h"==r||"v"==r||"g"==r)||"c"==l.toLowerCase()&&"i"==r||"r"==l.toLowerCase()&&"w"==r||"r"==l.toLowerCase()&&"h"==r||"u"==l.toLowerCase()&&"t"==r||"n"==l.toLowerCase()&&"o"==
r||"n"==l.toLowerCase()&&"s"==r||"n"==l.toLowerCase()&&"u"==r||"n"==l.toLowerCase()&&"w"==r)l=g,r="";"n"==l.toLowerCase()&&2<r.length&&"t0"==r.substring(0,2)&&(l=g.substring(0,3),r=g.substring(3));"r"==l.toLowerCase()&&2==r.length&&"wu"==r.substring(0,2)&&(l=g.substring(0,3),r="");var r=[l,r],l=r[0],r=r[1],u=h;switch(l.toLowerCase()){case "e":case "w":case "x":case "y":case "z":case "l":u=this.jM(l,r,n,q,Ff(l))==m?k:p;break;case "a":case "d":case "fh":case "fv":case "ci":case "g":case "fg":case "i":case "n":case "no":case "ns":case "nu":case "nw":case "rw":case "rwu":case "rh":case "u":case "ut":case "v":u=
this.iM(l,r,n,q,Gf(l))==m?k:p;break;case "f":case "j":case "q":case "t":case "nt0":u=this.kM(l,r,n,q,Hf(l))==m?k:p;break;case "b":case "c":case "h":case "k":case "o":case "p":case "r":case "s":s:{var u=[],w=[];this.fT(l,u,w);var D=[],N=[],M=h;for(M in u){var J=u[M],gb=w[M],gb=If(this,J)(l,r,n,q,gb);if(gb==m){u=k;break s}D.push(J);N.push(gb)}for(M in N)gb=N[M],m(g,gb);u=p}break;default:u=p}g=u}d=d&&g}a=d}return new Jf(b,c,a)};
function Ff(a){switch(a.toLowerCase()){case "e":return P.prototype.I8;case "w":return P.prototype.RM;case "x":return P.prototype.p$;case "y":return P.prototype.q$;case "z":return P.prototype.r$;case "l":return P.prototype.i$;default:return function(){}}}
function Gf(a){switch(a.toLowerCase()){case "a":return P.prototype.H8;case "d":return P.prototype.G8;case "fh":return P.prototype.K8;case "fv":return P.prototype.Y8;case "ci":return P.prototype.M8;case "g":return P.prototype.o$;case "fg":return P.prototype.J8;case "i":return P.prototype.d$;case "n":return P.prototype.ZB;case "no":return P.prototype.O8;case "nw":return P.prototype.R8;case "ns":return P.prototype.P8;case "nu":return P.prototype.Q8;case "rw":return P.prototype.U8;case "rwu":return P.prototype.V8;
case "rh":return P.prototype.T8;case "u":return P.prototype.s$;case "ut":return P.prototype.t$;case "v":return P.prototype.a$;default:return function(){}}}function Hf(a){switch(a.toLowerCase()){case "f":return P.prototype.N8;case "j":return P.prototype.aa;case "q":return P.prototype.j$;case "t":return P.prototype.X8;case "nt0":return P.prototype.u$;default:return function(){}}}
s.fT=function(a,b,c){switch(a.toLowerCase()){case "b":b.push(1,0),c.push(P.prototype.W9,P.prototype.V9);case "c":b.push(1,0),c.push(P.prototype.EM,P.prototype.E8);case "h":b.push(1,0);c.push(P.prototype.L8,P.prototype.HM);break;case "k":b.push(1,0);c.push(P.prototype.LM,P.prototype.c$);break;case "o":b.push(1,2);c.push(P.prototype.S8,P.prototype.ha);break;case "p":b.push(1,0);c.push(P.prototype.QM,P.prototype.b$);break;case "r":b.push(1,0);c.push(P.prototype.l$,P.prototype.k$);break;case "s":b.push(1,
0),c.push(P.prototype.W8,P.prototype.NM)}};function Kf(a,b,c,d,e){e.apply(c,[b]);a=a.substring(0,1);e.apply(d,[a==a.toUpperCase()])}s.jM=function(a,b,c,d,e){if(""==b)return 0;isFinite(b)&&(b=String(b));b=x(b)?/^\s*-?0x/i.test(b)?parseInt(b,16):parseInt(b,10):NaN;if(isNaN(b))return 1;Kf(a,b,c,d,e);return m};s.iM=function(a,b,c,d,e){if(""!=b)return 2;Kf(a,k,c,d,e);return m};s.kM=function(a,b,c,d,e){if(""==b)return 0;Kf(a,b,c,d,e);return m};
function If(a,b){switch(b){case 0:return y(a.jM,a);case 1:return y(a.iM,a);case 2:return y(a.kM,a);default:return function(){}}}function Jf(a,b,c){this.l=a;this.o=b;this.q=c}Jf.prototype.$j=function(){return this.q};function Lf(a){Mf(this,a)}function Nf(a){a.$==m&&(a.$=new Ef);return a.$}function Mf(a,b){a.r=[];b?x(b)?a.o=Nf(a).parse(b):a.o=b:a.o=Nf(a).parse("")}function Of(a,b,c,d){b||"number"==typeof b&&0==b||(b=h);var e=a.o.l;a=a.o.o;var g=c.call(e);b!=g&&(g!=h&&c.call(a),d.call(e,b))}function Pf(a,b){b&&(Qf(a,p),Of(a,p,P.prototype.$y,P.prototype.ZB));Of(a,b,P.prototype.QH,P.prototype.EM);return a}function Rf(a){Of(a,h,P.prototype.getHeight,P.prototype.HM)}
function Sf(a){Of(a,k,P.prototype.YH,P.prototype.LM);return a}function Tf(a,b){ja(b)&&(b=Math.max(b.width,b.height));b!=m&&(Uf(a),Rf(a));Of(a,b,P.prototype.fd,P.prototype.NM);return a}function Qf(a,b){b&&(Pf(a,p),Of(a,p,P.prototype.$y,P.prototype.ZB));Of(a,b,P.prototype.cI,P.prototype.QM)}function Uf(a){Of(a,h,P.prototype.YB,P.prototype.RM)}
Lf.prototype.q=function(){this.r.length=0;var a=this.o.l;a.eI()||a.fI()?a.fd()||Tf(this,0):(a=this.o.l,a.fd()||a.YB()||a.getHeight()||(Pf(this),Tf(this),Rf(this),Qf(this),Uf(this)));Vf(this,"s",P.prototype.fd);Vf(this,"w",P.prototype.YB);Wf(this,"c",P.prototype.QH);Vf(this,"c",P.prototype.B8,16,6);Wf(this,"d",P.prototype.YZ);Vf(this,"h",P.prototype.getHeight);Wf(this,"s",P.prototype.B_);Wf(this,"h",P.prototype.C8);Wf(this,"p",P.prototype.cI);Vf(this,"p",P.prototype.b_);Wf(this,"n",P.prototype.$y);
Vf(this,"r",P.prototype.y_);Wf(this,"r",P.prototype.z_);Wf(this,"fh",P.prototype.f_);Wf(this,"fv",P.prototype.I_);Wf(this,"ci",P.prototype.g_);Wf(this,"o",P.prototype.r_);Xf(this,"o",P.prototype.$);Xf(this,"j",P.prototype.r);Vf(this,"x",P.prototype.D_);Vf(this,"y",P.prototype.E_);Vf(this,"z",P.prototype.F_);Wf(this,"g",P.prototype.C_);Wf(this,"fg",P.prototype.d_);Vf(this,"e",P.prototype.a_);Xf(this,"f",P.prototype.h_);Wf(this,"k",P.prototype.YH);Vf(this,"k",P.prototype.c_);Wf(this,"u",P.prototype.eI);
Wf(this,"ut",P.prototype.fI);Wf(this,"i",P.prototype.i_);Wf(this,"a",P.prototype.ZZ);Wf(this,"b",P.prototype.XZ);Vf(this,"b",P.prototype.VZ);Xf(this,"t",P.prototype.D8);Xf(this,"nt0",P.prototype.H_);Wf(this,"v",P.prototype.$Z);Wf(this,"rw",P.prototype.w_);Wf(this,"rwu",P.prototype.x_);Wf(this,"nw",P.prototype.o_);Wf(this,"rh",P.prototype.v_);Wf(this,"no",P.prototype.l_);Xf(this,"q",P.prototype.u_);Wf(this,"ns",P.prototype.m_);Vf(this,"l",P.prototype.t_);Wf(this,"nu",P.prototype.n_);return this.r.join("-")};
function Yf(a,b){if(b==h)return"";var c=b-a.length;return 0>=c?"":xc("0",c)}function Vf(a,b,c,d,e){var g=c.apply(a.o.l,[]);if(g!=h&&g!=m){d=d==h||10!=d&&16!=d?10:d;var g=g.toString(d),l=new ad;l.yb(16==d?"0x":"");l.yb(Yf(g,e));l.yb(g);Zf(a,b,l.toString(),c)}}function Wf(a,b,c){c.apply(a.o.l,[])&&Zf(a,b,"",c)}function Xf(a,b,c){var d=c.apply(a.o.l,[]);d&&Zf(a,b,d,c)}function Zf(a,b,c,d){d.apply(a.o.o,[])&&(b=b.substring(0,1).toUpperCase()+b.substring(1));a.r.push(b+c)};var $f=/^[^\/]*\/\//;function ag(){}ag.prototype.parse=function(a){return new dg(a)};function dg(a){this.o=a;this.r="";(a=this.o.match($f))&&a[0]?(this.r=a[0],a=this.r.match(/\w+/)?this.o:"http://"+this.o.substring(this.r.length)):a="http://"+this.o;this.q=Ae(a,k);this.ha=k;this.Ba=p}var eg=["image","proxy","public"];
function fg(a){if(a.l==h){a.l=a.q.Cf.substring(1).split("/");var b=a.l.length;if(7==b||2==b)a.l[0]&&Ba(eg,a.l[0])||(a.ha=p);else if(7<b||2<b&&5>b||0==b)a.ha=p;if(2>=b){a.Ba=k;var b=b-1,c=a.l[b],d=c.indexOf("\x3d");-1!=d&&(a.l[b]=c.substr(0,d),a.l.push(c.substr(d+1)))}}return a.l}dg.prototype.$j=function(){fg(this);return this.ha};function gg(a){fg(a);return a.Ba}dg.prototype.dc=function(){var a=this.q.xi;return this.q.dc()+(a?":"+a:"")};
function hg(a){if(a.aa!=h)return a.aa;var b=fg(a);b[0]&&Ba(eg,b[0])?a.aa=b[0]:a.aa=m;return a.aa}function ig(a){switch(fg(a).length){case 7:return k;case 6:return hg(a)==m;case 5:return p;case 3:return k;case 2:return hg(a)==m;case 1:return p;default:return p}}
function jg(a,b){var c;if(gg(a))t:{c=hg(a)!=m?1:0;switch(b){case 6:c=0+c;break;case 4:if(!ig(a)){c=m;break t}c=1+c;break;default:c=m;break t}c=fg(a)[c]}else t:{c=hg(a)!=m?1:0;switch(b){case 0:c=0+c;break;case 1:c=1+c;break;case 2:c=2+c;break;case 3:c=3+c;break;case 4:if(!ig(a)){c=m;break t}c=4+c;break;case 5:var d=ig(a)?1:0;c=4+c+d;break;default:c=m;break t}c=fg(a)[c]}return c}dg.prototype.Jb=function(){this.$==h&&(this.$=jg(this,0));return this.$};
function kg(a){a.Fa==h&&(a.Fa=jg(a,1));return a.Fa}function lg(a){a.Ca==h&&(a.Ca=jg(a,2));return a.Ca}function mg(a){a.Ka==h&&(a.Ka=jg(a,3));return a.Ka}dg.prototype.Wh=function(){this.ka==h&&(this.ka=jg(this,4));return this.ka};function ng(a){a.ya==h&&(a.ya=jg(a,5));return a.ya};function og(a){a instanceof dg?this.l=a:(pg==h&&(pg=new ag),this.l=pg.parse(a.toString()));a=this.l;if(a.wa==h){var b=a.Wh();b||(b="");a.wa=(new Ef).parse(b)}Mf(this,a.wa);this.ka=this.l.r;this.ha=this.l.dc();this.aa=this.l.q.l.toString()}var pg;A(og,Lf);
og.prototype.q=function(){if(!this.l.$j())return this.l.o;var a=og.ra.q.call(this),b=[];hg(this.l)!=m&&b.push(hg(this.l));if(gg(this.l)){var c=this.l;c.Ea==h&&(c.Ea=jg(c,6));b.push(c.Ea+(a?"\x3d"+a:""))}else b.push(this.l.Jb()),b.push(kg(this.l)),b.push(lg(this.l)),b.push(mg(this.l)),a&&b.push(a),b.push(ng(this.l));a=b.join("/");return this.ka+this.ha+"/"+a+(this.aa?"?"+this.aa:"")};function qg(a){this.o=0<a.indexOf("/",a.length-1)?a:a+"/";this.l=new F;Dc(rg,function(a,c){this.l.set(a,sg[c])},this)}
var rg={$P:"cleardot",RP:"bubble",TP:"bubble_new",VD:"busy",VP:"busy_video",bQ:"close",aE:"dropdown",jQ:"dropdown_hover",IDLE:"idle",uQ:"idle_video",KQ:"maximize",QQ:"minimize",cR:"muc_icon",fR:"offline",gR:"online",hR:"online_video",kR:"phone",nR:"popin",oR:"popout",qR:"portrait",uR:"voice/red-phone",NS:"voice/phone-presence"},sg={$P:"cleardot-icon",RP:"bubble-icon",TP:"bubble_new-icon",VD:"busy-icon",VP:"busy_video-icon",bQ:"close-icon",aE:"dropdown-icon",jQ:"dropdown_hover-icon",IDLE:"idle-icon",
uQ:"idle_video-icon",KQ:"maximize-icon",QQ:"minimize-icon",cR:"muc_icon-icon",fR:"offline-icon",gR:"online-icon",hR:"online_video-icon",kR:"phone-icon",nR:"popin-icon",oR:"popout-icon",qR:"portrait-icon",uR:"voice_red-phone-icon",NS:"voice_phone-presence-icon"};function tg(a,b,c){return[a.o,"images/",b,c?"_favicon":"",c?".ico":".png"].join("")}function ug(a,b,c){var d;c=vg(b,c);return tg(a,c,b==m?p:d)}
function vg(a,b){var c;switch(a||m){case m:c="cleardot";break;case "u":c="offline";break;case "w":case "i":c=b?"idle_video":"idle";break;case "b":c=b?"busy_video":"busy";break;case "c":case "a":c=b?"online_video":"online";break;default:c="offline"}return c}function wg(a){switch(a){case "a":case "c":return"roster_row_online";case "b":return"roster_row_busy";case "i":case "w":return"roster_row_idle"}return""}
function xg(a){switch(a){case "offline":return"Offline";case "online":return"Verf\u00fcgbar";case "online_video":return"Verf\u00fcgbar (Video aktiviert)";case "idle":return"Inaktiv";case "idle_video":return"Inaktiv (Video aktiviert)";case "busy":return"Nicht verf\u00fcgbar";case "busy_video":return"Nicht verf\u00fcgbar (Video aktiviert)";case "phone":return"Mobil";default:return""}}
function yg(a,b,c){var d="bubble";c&&(d+=" "+a.l.get(b));switch(b){case "idle_video":case "busy_video":case "online_video":d+=" video_bubble";break;case "bubble":case "bubble_new":d+=" new_bubble"}return d};var zg={Yo:"ce",sE:"si",xQ:"sp"},Ag={Yo:"ce",QD:"ai",Jr:"pi",Rw:"na",Sw:"nt",fS:"si",tE:"sa",vS:"sit",Km:"st",Yw:"sp",XS:"wa"},Bg={tR:"ql"},Cg={Oca:"mn",Ada:"mn",Uca:"fb",eda:"hb",fda:"hi",FQ:"lc",iR:"oa",jR:"ol",Tda:"qb",Vda:"rb",Dea:"vb"};function Dg(a){return a=""+('\x3cdiv id\x3d"'+a.Kb.Yo+'" class\x3d"me_widget_container"\x3e\x3cdiv class\x3d"me_widget_area" id\x3d'+a.Kb.XS+'\x3e\x3ctable cellpadding\x3d"0" cellspacing\x3d"0" border\x3d"0" class\x3d"me_entry_status_table"\x3e\x3ctr\x3e\x3ctd class\x3d"me_entry_status"\x3e\x3cdiv id\x3d"'+a.Kb.Jr+'" class\x3d"'+O(a.Af)+'" onselectstart\x3d"return false;"\x3e \x3c/div\x3e\x3cdiv id\x3d"'+a.Kb.Rw+'" class\x3d"me_entry_area" tabindex\x3d-1\x3e\x3cnobr\x3e\x3cdiv id\x3d"'+a.Kb.Sw+'" class\x3d"me_entry_name" tabindex\x3d-1 onselectstart\x3d"return false"\x3e'+
O(a.Wl)+'\x3c/div\x3e\x3cdiv id\x3d"'+a.Kb.fS+'" class\x3d"me_sign_in" onselectstart\x3d"return false"\x3eIm Chat anmelden\x3c/div\x3e\x3c/nobr\x3e\x3c/div\x3e\x3c/td\x3e\x3ctd valign\x3d"middle" class\x3d"roster_title_icon_cell" tabindex\x3d"-1" onselectstart\x3d"return false"\x3e\x3cdiv id\x3d"'+a.Kb.Yw+'" class\x3d"roster_entry_image_portrait roster_header_dropdown '+O(a.uY)+'" alt\x3d"Hier zum Anzeigen des Men\u00fcs klicken" tabindex\x3d1 role\x3d"menu" aria-haspopup\x3d"true"\x3e\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e\x3c/div\x3e\x3c/div\x3e')}
;function Eg(a){a=a||{};var b='\x3cdiv class\x3d"roster_separator" onselectstart\x3d"return false"\x3e\x3c/div\x3e\x3cdiv class\x3d"menu_container" id\x3d"'+O(a.Kb.FQ)+'"\x3e\x3ctable class\x3d"roster_footer" border\x3d0 cellspacing\x3d0 cellpadding\x3d0 onselectstart\x3d"return false"\x3e\x3ctr\x3e';a.gj||(b+='\x3ctd valign\x3d"top"\x3e\x3cbutton id\x3d"'+O(a.Kb.jR)+'" class\x3d"roster_entry roster_links_td" style\x3d"padding:0px 0px 2px 3px"\x3e\x3cspan class\x3d"roster_links"\x3eOptionen\x3c/span\x3e\x3cspan id\x3d"'+
O(a.Kb.iR)+'" class\x3d"roster_links_arrow"\x3e\x26#x25bc;\x3c/span\x3e\x3c/button\x3e\x3c/td\x3e');return b+"\x3c/tr\x3e\x3c/table\x3e\x3c/div\x3e"};function Fg(a){return'\x3cli id\x3d"'+a.oF+'" class\x3d"roster_list_item" aria-labelledby\x3d"'+a.zj+'" role\x3d"listitem menuitem"\x3e'+Gg(a)+"\x3c/li\x3e"}
function Gg(a){return a.lP?'\x3cdiv class\x3d"roster_row '+O(a.iC)+(a.reverse?" roster_row_reverse":"")+'"\x3e\x3cbutton id\x3d"'+a.zj+'" tabindex\x3d"-1" aria-label\x3d"'+O(a.TE)+'" contact_jid\x3d"'+O(a.uG)+'" '+(a.ah?' title\x3d"'+O(a.ah)+'" ':"")+"\x3e"+uf(a.Ur)+uf(a.Nm)+'\x3cdiv id\x3d"'+O(a.Xn)+'" class\x3d"roster_name"'+(a.ah?' title\x3d"'+O(a.ah)+'"':"")+O(wf(a.yh))+"\x3e"+uf(a.yh)+'\x3c/div\x3e\x3cdiv id\x3d"'+a.Zv+'" class\x3d"roster_row_status"'+(a.fh?' title\x3d"'+O(a.fh)+'" '+O(wf(a.fh))+
" ":"")+"\x3e"+O(a.fh)+"\x3c/div\x3e\x3c/button\x3e\x3c/div\x3e":'\x3cbutton id\x3d"'+a.zj+'" class\x3d"roster_row '+O(a.iC)+'" tabindex\x3d"-1" aria-label\x3d"'+O(a.TE)+'" contact_jid\x3d"'+O(a.uG)+'"'+(a.ah?' title\x3d"'+O(a.ah)+'" ':"")+'\x3e\x3ctable class\x3d"roster_row_table"\x3e \x3ctbody\x3e\x3ctr\x3e'+(a.Lm?a.reverse?'\x3ctd id\x3d"'+O(a.Lm)+'" class\x3d"roster_row_avatar roster_reverse"\x3e'+uf(a.Ur)+'\x3c/td\x3e\x3ctd id\x3d"'+O(a.Xn)+'" class\x3d"roster_row_name roster_reverse"\x3e\x3cdiv class\x3d"roster_name" '+
O(wf(a.yh))+" \x3e"+uf(a.yh)+'\x3c/div\x3e\x3c/td\x3e\x3ctd id\x3d"'+O(a.lp)+'" class\x3d"roster_row_bubble roster_reverse"\x3e'+uf(a.Nm)+"\x3c/td\x3e":'\x3ctd id\x3d"'+O(a.lp)+'" class\x3d"roster_row_bubble"\x3e'+uf(a.Nm)+'\x3c/td\x3e\x3ctd id\x3d"'+O(a.Xn)+'" class\x3d"roster_row_name"\x3e\x3cdiv class\x3d"roster_name" '+(a.ah?' title\x3d"'+O(a.ah)+'"':"")+"  "+O(wf(a.yh))+"\x3e"+uf(a.yh)+'\x3c/div\x3e\x3c/td\x3e\x3ctd id\x3d"'+O(a.Lm)+'" class\x3droster_row_avatar\x3e'+uf(a.Ur)+"\x3c/td\x3e":a.reverse?
'\x3ctd id\x3d"'+O(a.Xn)+'" class\x3d"roster_row_name roster_reverse"\x3e\x3cdiv class\x3d"roster_name" '+(a.ah?' title\x3d"'+O(a.ah)+'"':"")+" "+O(wf(a.yh))+"\x3e"+uf(a.yh)+'\x3c/div\x3e\x3c/td\x3e\x3ctd id\x3d"'+O(a.lp)+'" class\x3d"roster_row_bubble roster_reverse"\x3e'+uf(a.Nm)+"\x3c/td\x3e":'\x3ctd id\x3d"'+O(a.lp)+'" class\x3d"roster_row_bubble"\x3e'+uf(a.Nm)+'\x3c/td\x3e\x3ctd id\x3d"'+O(a.Xn)+'" class\x3d"roster_row_name"\x3e\x3cdiv class\x3d"roster_name" '+(a.ah?' title\x3d"'+O(a.ah)+'"':
"")+" "+O(wf(a.yh))+"\x3e"+uf(a.yh)+"\x3c/div\x3e\x3c/td\x3e")+"\x3c/tr\x3e\x3ctr "+(0==a.Fo.length?'class\x3d"roster_row_status roster_status_row_hidden':'class\x3d"roster_row_status')+'" id\x3d"'+a.rO+'"\x3e'+(a.reverse?"\x3ctd "+(a.Lm?' colspan\x3d"2" ':"")+'id\x3d"'+a.Zv+'"\x3e\x3cdiv class\x3d"roster_entry_status roster_reverse"'+(a.fh?'title\x3d"'+O(a.fh)+'"':"")+" "+O(wf(a.Fo))+"\x3e"+uf(a.Fo)+"\x3c/div\x3e\x3c/td\x3e\x3ctd \x3e \x3c/td\x3e":"\x3ctd\x3e \x3c/td\x3e\x3ctd "+(a.Lm?' colspan\x3d"2" ':
"")+'id\x3d"'+a.Zv+'"\x3e\x3cdiv class\x3d"roster_entry_status"'+(a.fh?'title\x3d"'+O(a.fh)+'"':"")+" "+O(wf(a.Fo))+"\x3e"+uf(a.Fo)+"\x3c/div\x3e\x3c/td\x3e")+"\x3c/tr\x3e\x3c/tbody\x3e \x3c/table\x3e\x3c/button\x3e"};function Hg(a){return a=""+((a.lA?'\x3cdiv class\x3d"roster_buzz_header"\x3e'+O(a.lA)+"\x3c/div\x3e":"")+'\x3cul id\x3d"'+a.id.tR+'" class\x3d"roster_buzz" onselectstart\x3d"return false" role\x3d"list menu"'+(a.WG?" aria-activedescendant\x3d"+O(a.WG)+" ":"")+'aria-label\x3d"Kontaktmen\u00fc"\x3e'+uf(a.pN)+"\x3c/ul\x3e")};function Ig(a){var b='\x3cdiv id\x3d"'+a.Kb.Yo+'" class\x3d"me_widget_container"\x3e\x3cdiv class\x3d"me_widget_area"\x3e'+(a.Wf?"":'\x3cdiv id\x3d"'+a.Kb.Jr+'" class\x3d"'+O(a.Af)+'" onselectstart\x3d"return false;"\x3e \x3c/div\x3e\x3cdiv id\x3d"'+a.Kb.Rw+'" class\x3d"me_entry_area'+(a.Ji?" me_entry_avatar_padding":"")+'" tabindex\x3d-1\x3e\x3cnobr\x3e\x3cdiv id\x3d"'+a.Kb.Sw+'" class\x3d"me_entry_name" tabindex\x3d-1 onselectstart\x3d"return false" contact_jid\x3d"'+O(a.fB)+'"'+O(wf(a.Wl))+"\x3e"+
O(a.Wl)+"\x3c/div\x3e\x3c/nobr\x3e\x3c/div\x3e")+'\x3ctable cellpadding\x3d"0" cellspacing\x3d"0" border\x3d"0" role\x3d"combobox" class\x3d"me_entry_status_table'+(a.Ji?" me_entry_avatar_padding":"")+'"\x3e\x3ctr\x3e\x3ctd '+(a.Wf?'style\x3d"width:1px"':"")+'class\x3d"me_entry_status_left_cell"\x3e\x3c/td\x3e\x3ctd id\x3d"'+a.Kb.tE+'" valign\x3d"top" class\x3d"me_entry_status"\x3e'+(a.Wf?'\x3cdiv id\x3d"'+a.Kb.Jr+'" class\x3d"'+O(a.Af)+'" onselectstart\x3d"return false;"\x3e \x3c/div\x3e':""),b=
a.lq?b+('\x3cdiv style\x3d"padding-right: 5px"\x3e\x3clabel for\x3d"'+a.Kb.Km+'" class\x3d"me_entry_status_label"\x3eChat-Status\x3c/label\x3e\x3cinput type\x3d"text" id\x3d"'+a.Kb.Km+'" tabindex\x3d"0" class\x3d"me_entry_status_text" spellcheck\x3d"false" value\x3d"'+O(a.statusText)+'" style\x3d"'+(a.Ll?"margin: 0px 1px;":"")+'" /\x3e\x3c/div\x3e'):b+('\x3cdiv id\x3d"'+a.Kb.Km+'" class\x3d"me_entry_status_static_div"\x3e'+Jg(a)+"\x3c/div\x3e");return b+="\x3c/td\x3e"+(a.lq?'\x3ctd valign\x3d"middle" id\x3d"'+
a.Kb.Yw+'" class\x3d"me_dropframe" tabindex\x3d"-1" onselectstart\x3d"return false"\x3e\x26#x25bc;\x3c/td\x3e':"")+'\x3ctd class\x3d"me_entry_status_right_cell"\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e'+(a.Ji?'\x3cimg id\x3d"'+a.Kb.QD+'" src\x3d"'+O(a.Ji)+'" class\x3d"me_avatar_image" /\x3e':"")+'\x3c/div\x3e\x3cdiv class\x3d"roster_separator" onselectstart\x3d"return false"\x3e\x3c/div\x3e\x3c/div\x3e'}
function Jg(a){return'\x3cnobr\x3e\x3cspan id\x3d"'+a.Kb.vS+'" class\x3d"me_entry_status_static_text"'+(a.fh?' title\x3d"'+O(a.fh)+'" ':"")+"\x3e"+O(a.statusText)+"\x3c/span\x3e"+(a.Co?'\x3cspan class\x3d"me_entry_status_static_arrow"\x3e\x26#x25be;\x3c/span\x3e':"")+"\x3c/nobr\x3e"};function Kg(a){return'\x3cdiv class\x3d"roster_search_widget"\x3e\x3cdiv style\x3d"width: 100%; text-align: center"\x3e\x3cdiv id\x3d"'+O(a.Kb.Yo)+'" class\x3d"CSS_ME_ENTRY_SEARCH_DIV"\x3e\x3cdiv style\x3d"position: relative"\x3e\x3cdiv class\x3d"me_entry_search_hint"\x3e\x3c/div\x3e\x3cinput type\x3d"text" id\x3d"'+O(a.Kb.sE)+'" class\x3d"me_entry_search" value\x3d"" autocomplete\x3d"off" /\x3e\x3clabel id\x3d"'+O(a.Kb.xQ)+'" for\x3d"'+O(a.Kb.sE)+'" class\x3d"me_entry_search_label"\x3e'+O(a.JG)+
"\x3c/label\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e"};
Sb("sy3");Vb();
}catch(e){_DumpException(e)}
try{
function M$(){this.r={}}M$.prototype.o=m;M$.prototype.l=m;M$.prototype.q=m;Ub("lite");function N$(a,b,c){this.l=a;this.jid=O$(b);this.zC=c}N$.prototype.show="u";function P$(a,b){if(a.jid==O$(b.Pa())){switch(b.Ec()){case 5:case 6:a.show="a";break;case 3:case 2:a.show="w";break;case 4:a.show="b";break;default:a.show="u"}a.status=b.getStatus();var c=p,d=p,e=b.Xe();e!=m&&(c=0!=(e&8)&&0!=(e&16),d=0!=(e&256));a.di=c;a.ha=d;return k}return p}
function Q$(a,b){if(a.jid!=O$(b.Pa()))return p;a.$=b.getName();var c=b.ea[3]||"//ssl.gstatic.com/s2/profiles/images/silhouette80.png",d=new L(c);d.Al||(d=new L(a.l.Gd.toString()+"image?h\x3d"+c),d.l.add("authuser",ce(ee(a.l))));a.aa=d.toString();return k}N$.prototype.wl=function(a){return this.o!=m&&""!=this.o?Sf(Pf(Tf(new og(this.o),a),k)).q():m};N$.prototype.pd=function(){return this.aa};
N$.prototype.getName=function(){return"homepage"==this.l.hd?this.q||this.r||this.$||"":this.r||this.$||this.q||""};function O$(a){if(a){var b=a.indexOf("/");return 0<=b?a.substring(0,b):a}return m};function R$(a){this.l=a;this.ha=new qg(a.Gd);this.$l=new M$;this.aa={};this.o=new N$(this.l,ee(this.l).Pa(),"");this.r=[];for(a=0;a<this.l.Ka.length;++a){var b=dd(this.l.Ka[a]);switch(b[0]){case "ru":var b=new yf(b),c=m;b&&(c=new N$(this.l,b.Pa(),String(b.Rg())),c.r=b.ea[2],c.q=b.ea[16],c.o=b.wl());b=c;b.jid==ee(this.l).Pa()?this.o=b:(this.r.push(b),this.aa[b.zC]=b);break;case "p":var d=new Bf(b);if(this.o&&P$(this.o,d))break;for(c=this.r.length-1;0<=c&&(b=this.r[c],!P$(b,d));c--);break;case "vc":if(!S$(this,
"sr3"))break;d=new zf(b);if(this.o&&Q$(this.o,d))break;for(c=this.r.length-1;0<=c&&(b=this.r[c],!Q$(b,d));c--);break;case "ql":b.shift();this.$=b;break;case "me":this.ka=(new Boolean(b[2])).valueOf()}}}var Tha=t.navigator&&-1!=t.navigator.userAgent.indexOf("MSIE");s=R$.prototype;
s.render=function(a,b){var c=T$(this);if(!S$(this,"le")||0!=c.length){var d=this.q=document.createElement("div"),e;e=new ad;var g,l=m,n=p;"homepage"==this.l.hd?(l=S$(this,"rcq")?"Letzte Chats":"",g=Xd(ge(this.l))?"Chatten mit...":"Nachricht senden an...",n=S$(this,"ump")):g=this.l.o||this.l.q?Xd(ge(this.l))?"Chatten mit...":"Nachricht senden an...":"In Kontakten suchen...";g={Kb:zg,JG:g};var q={Kb:Ag,Ji:m,Af:this.l.Wf?"me_status_entry_image":"me_entry_image",Wl:this.o.getName()};n||Cc(q,{mF:ug(this.ha,
m),Wf:this.l.Wf,statusText:"Wird geladen...",Co:p,Ll:Tha,lq:this.l.ya});this.l.jd?(n?e.yb(Dg(q)):e.yb(Ig(q)),e.yb(Kg(g))):(e.yb(Kg(g)),n?e.yb(Dg(q)):e.yb(Ig(q)));e.yb(Hg({id:Bg,lA:l,pN:Uha(this)}));this.l.Va||e.yb(Eg({Kb:Cg,gj:this.l.gj}));b&&e.yb('\x3cdiv\x3e\x3ca href\x3d"javascript:GoogleChat_LoadFull()"\x3e[load full]\x3c/a\x3e\x3c/div\x3e');e='\x3cdiv class\x3d"CSS_CHAT_ROSTER"\x3e'+uf(e.toString())+"\x3c/div\x3e";d.innerHTML=e;a.appendChild(this.q);this.$l.q=z();for(d=0;d<c.length;d++)U$(this,
"qlrbtn"+d,y(this.j7,this,c[d].jid));this.l.Va||this.l.gj||U$(this,"ol",y(this.i7,this,1));if(c=document.getElementById("si"))c.onkeyup=y(this.QL,this,p),c.onkeypress=y(this.QL,this,k),c.onblur=y(this.g7,this,k)}};s.destroy=function(){this.q&&(this.q.parentNode.removeChild(this.q),this.q=m)};
function Uha(a){for(var b=new ad,c=T$(a),d=0;d<c.length;d++){var e=c[d],g;g=e.show;if(e.ha)g="b"==g?"busy":"phone";else{var l="u"==g;g=vg(g,e.di&&!l)}g='\x3cdiv class\x3d"'+yg(a.ha,g,k)+'" title\x3d"'+xg(g)+'" \x3e\x3c/div\x3e';var n=a,l=e;if(n.l.Ba)if(S$(n,"sr3")){var q=document.createElement("IMG");Ve(q,"hidden","true");q.title="";q.alt="";n=Zd(ge(n.l))?l.pd():"//ssl.gstatic.com/s2/profiles/images/silhouette80.png";q.src=l.wl(32)||n;l=Dd(q)}else l='\x3cdiv class\x3d"roster_default_avatar"\x3e\x3c/div\x3e';
else l="";var q=yc(e.getName()||""),r=a.l.q||a.l.o,n=a.l.$?m:yc(e.status||""),r=a.l.$||!r?"":e.status||"",e=wg(e.show);b.yb(Fg({lP:Wd(ge(a.l)),oF:"qlrl"+d,zj:"qlrbtn"+d,lp:"qlrbc"+d,Xn:"qlrnc"+d,Lm:a.l.Ba?"qlrac"+d:m,rO:"qlrsr"+d,Zv:"qlrsc"+d,reverse:a.l.Oa,Nm:g,Ur:l,yh:q,Fo:n||"",fh:r,iC:e}))}return b.toString()}function T$(a){if(a.l.Nb&&a.ka)return[];var b=[];if(a.$)for(var c=0;c<a.$.length;c++){var d=a.aa[a.$[c]];d&&b.push(d)}return b}s.j7=function(a){this.$l.r[a]=k};
s.i7=function(a){var b=this.$l.o;b&&b!=a&&(b=document.getElementById("ol"),this.eN(b,"roster_entry_pending"),b.onmouseover=m,b.onmouseout=m,b.style.cursor="",b.firstChild&&(b.firstChild.style.cursor=""));this.$l.o=a};s.g$=function(a,b){this.zE(a,"roster_entry_pending");a.onmouseover=m;a.onmouseout=m;a.style.cursor="wait";a.firstChild&&(a.firstChild.style.cursor="wait");V$();b()};function V$(){document.getElementById("st").style.fontWeight="bold"}
s.QL=function(a){var b=document.getElementById("si");a=!a&&""==b.value;document.getElementById("sp").style.display=a?"":"none";b.style.cursor=a?"":"wait";V$();this.$l.l=b.value};s.g7=function(){""==document.getElementById("si").value&&(this.$l.l=m)};function U$(a,b,c){b=document.getElementById(b);b.onmouseover=y(a.zE,a,b,"roster_entry_hover");b.onmouseout=y(a.eN,a,b,"roster_entry_hover");b.onmousedown=y(a.g$,a,b,c)}s.zE=function(a,b){0>a.className.indexOf(b)&&(a.className+=" "+b)};
s.eN=function(a,b){for(var c=a.className&&a.className.split?a.className.split(/\s+/):[],d=[],e=0;e<c.length;e++)c[e]&&c[e]!=b&&d.push(c[e]);a.className=d.join(" ")};function S$(a,b){for(var c=a.l.Ua,d=0;d<c.length;d++)if(c[d]==b)return k;return p};function W$(a){this.l=a;this.o=y(this.onMessage,this);this.$q()}A(W$,C);W$.prototype.xa=function(){W$.ra.xa.call(this);if(this.isSupported()){var a=X$(this);a.addEventListener?a.removeEventListener("message",this.o,p):a.detachEvent("onmessage",this.o)}this.l=m};W$.prototype.$q=function(){if(this.isSupported()){var a=X$(this);a.addEventListener?a.addEventListener("message",this.o,p):a.attachEvent("onmessage",this.o);return k}return p};
W$.prototype.isSupported=function(){var a=X$(this);return a!=m&&(v(a.addEventListener)||v(a.attachEvent))};function X$(a){return a.l.postMessage?a.l:a.l.document.postMessage?a.l.document:m};function Y$(a,b){W$.call(this,a);this.q=b}A(Y$,W$);Y$.prototype.onMessage=function(a){a.data&&0==a.data.indexOf("_GCX_")&&(a.source.postMessage(a.data,a.origin),this.q(),this.Ga())};function Z$(a){this.$=a}Z$.prototype.load=function(a,b){this.o=a;this.l=p;var c=document.createElement("script");c.onreadystatechange=y(this.r,this,c);c.onload=y(this.aa,this);c.src=this.$;document.body.appendChild(c);c=b||6E4;this.q=window.setTimeout(y(this.load,this,a,2*c),c)};Z$.prototype.r=function(a){if("complete"==a.readyState||"loaded"==a.readyState)window.clearTimeout(this.q),this.l||(this.l=k,this.o())};Z$.prototype.aa=function(){window.clearTimeout(this.q);this.l||(this.l=k,this.o())};function $$(a){this.l=a;if(a=a.Ua!=m)t:{a=this.l.Ua;for(var b=0;b<a.length;b++)if("ld"==a[b]){a=k;break t}a=p}this.r=a}$$.prototype.ha=function(){this.ka.Ga();this.q()};$$.prototype.q=function(){(new Z$(this.l.Ah)).load(y(this.$,this))};$$.prototype.aa=function(){this.o.destroy()};$$.prototype.$=function(){window.GoogleChat_InitFull(this.l,y(this.aa,this),this.o.$l)};
zc("GoogleChat_Init",function(a){!ga(a.Ka)&&ia(window.init)?(delete window.GoogleChat_Init,window.init()):(a=new $$(a),a.o=new R$(a.l),a.o.render(document.body,a.r),a.r?(a=y(a.q,a),zc("GoogleChat_LoadFull",a,h)):a.l.wj?a.ka=new Y$(window,y(a.ha,a)):a.q())},h);
Sb("lite");Vb();
}catch(e){_DumpException(e)}

// Copyright 2002-2013 Google Inc.
